version: "3.8"
services:
  php:
    container_name: php74
    build: ./docker/php74/
    depends_on:
      - mysql
    ports:
      - "8100:80"
    volumes:
      - ./code/public/:/var/www/html/
  mysql:
    container_name: mysql8
    image: mysql:8.0.22
    restart: always
    ports:
      - "9906:3306"
    volumes:
    - ./dbdata/:/var/www/mysql/
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: test
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_PASSWORD=test
      - PMA_USER=root
